Problem 1: Enumeration of classes used so far

Classes that we have used in our previous Assignment are:
    
    1,pandas.read_csv()
    2,matplotlib.show()
    3,sklearn,ensemble

In [ ]:
Problem 2: Enumeration of method and instance variable used so far


Method:
    1, pandas.loc()
    2, pandas.iloc()
    3, numpy.sum()
    4, numpy.reshape()
    5, numpy.ravel()
    
instance variable:
    
    1, ndarry.shape
    2, ndarry.ndim
    3, ndarry.dtype
    4, ndarry.size
    5, ndarry.data

In [ ]:
Problem 3: Creating a standardized class by scratch

In [1]:
import numpy as np

class ScratchStandardScaler():
    
    def fit(self, X):
        
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)
        pass
    def transform(self, X):
    
        X_scaled = (X-self.mean_)/self.var_
        pass
        return X_scaled

from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("Average : {}".format(scratch_scaler.mean_))
print("Dispersed : {}".format(scratch_scaler.var_))
X_std= scratch_scaler.transform(X)
print(X_std)

Average : [4.86 3.31 1.45 0.22]
Dispersed : [0.0764 0.0849 0.0105 0.0056]
[[  3.14136126   2.23792697  -4.76190476  -3.57142857]
 [  0.52356021  -3.65135453  -4.76190476  -3.57142857]
 [ -2.09424084  -1.29564193 -14.28571429  -3.57142857]
 [ -3.40314136  -2.47349823   4.76190476  -3.57142857]
 [  1.83246073   3.41578327  -4.76190476  -3.57142857]
 [  7.06806283   6.94935218  23.80952381  32.14285714]
 [ -3.40314136   1.06007067  -4.76190476  14.28571429]
 [  1.83246073   1.06007067   4.76190476  -3.57142857]
 [ -6.02094241  -4.82921084  -4.76190476  -3.57142857]
 [  0.52356021  -2.47349823   4.76190476 -21.42857143]]


Problem 4: Creating a class that performs 4 arithmetic operations¶

In [2]:
def type_judge(value_to_judge):
    if not isinstance(value_to_judge, (int,float)):
        print("Please input only numbers")
        return False
    else:
        return True

class ArthClass():
        
    def __init__(self, value):
        if(type_judge(value)):
            self.value = value
            print("Initial value {} set".format(self.value))
        else:
            self.value = value
        
    def add(self, value2):
        
        if type_judge(self.value) and type_judge(value2):
            self.value += value2
        else:
            self.value = "can not be calculated because one of the values is not a number"
        
    def sub(self, value2):
        
        if type_judge(self.value) and type_judge(value2):
            self.value -= value2
        else:
            self.value = "can not be calculated because one of the values is not a number"
            
    def mult(self, value2):
        
        if type_judge(self.value) and type_judge(value2):
            self.value *= value2
        else:
            self.value = "can not be calculated because one of the values is not a number"
    
    def div(self, value2):
        
        if type_judge(self.value) and type_judge(value2):
            self.value /= value2
        else:
            self.value = "can not be calculated because one of the values is not a number"
        
example = ArthClass(5)
print("value : {}".format(example.value))
example.add(3)
print("addition value : {}".format(example.value))

example2 = ArthClass("k")
example2.sub(3)
print("subtraction value : {}".format(example2.value))

example.mult(3)
print("multiplication value : {}".format(example.value))
example.div("k")
print("division value : {}".format(example.value))

Initial value 5 set
value : 5
addition value : 8
Please input only numbers
Please input only numbers
subtraction value : can not be calculated because one of the values is not a number
multiplication value : 24
Please input only numbers
division value : can not be calculated because one of the values is not a number
